### ISSUE TITLE
Cloud card cursor should be pointer over card

### ISSUE THREAD

**Issue by toteos** [Colinwielga/Wanderer-Cordova#100]

**Comment by Prototypist1** [comment]
8 points

**Comment by toteos** [comment]
It was such a mess that I had to get my gloves out for this one:
https://github.com/Colinwielga/Wanderer-Cordova/commit/b415a37bb5ae55e83db5f55c5cb6988756bc0779
(Get it, "gloves"? I made the cursor turn into a hand, which looks like a glove. Why do gloves look like hands, though? Hm, I'll have to think about that over lunch.)

But it was worth it! I'm going to spend my points on the hottest skins.

**Comment by Prototypist1** [comment]
Does it work with dark mode?

**Comment by toteos** [comment]
😡
