### ISSUE TITLE
Cloud card normalization is still borked

### ISSUE THREAD

**Issue by toteos** [Colinwielga/Wanderer-Cordova#105]
Examples:
![image](https://user-images.githubusercontent.com/7977020/100962594-9b781400-34f2-11eb-840c-00c2e711d79f.png)
![image](https://user-images.githubusercontent.com/7977020/100962793-0aee0380-34f3-11eb-834e-b1abf4b22584.png)

**Comment by SeigneurF** [comment]
order fixed, and added commas for clarity.
