### ISSUE TITLE
I want to report an issue about drop shadow compatibility with dark mode

### ISSUE THREAD

**Issue by toteos** [Colinwielga/Wanderer-Cordova#106]
@Colinwielga 
Can I make the issue?

**Comment by toteos** [comment]
Eek, meant to tag @Prototypist1 

Don't punish me, overlord!

**Comment by Prototypist1** [comment]
How much for the report?

**Comment by toteos** [comment]
2 points should be good. 1 point for the bug discovery, 1 point for making the issue? I have this screenshot clogging up my clipboard, gotta paste it soon or my productivity is going to take a nosedive!

**Comment by Prototypist1** [comment]
No time to haggle. 1 sp or pass.

**Comment by toteos** [comment]
Pass, not my problem.

Here's the screenshot, though, since my trash can is full:
![image](https://user-images.githubusercontent.com/7977020/102170435-56dd6880-3e62-11eb-92ac-7e7c2b07932a.png)

**Comment by toteos** [comment]
This dude got "fixed" in #113 if anyone cares.
