### ISSUE TITLE
shadow should be a glow in dark mode

### ISSUE THREAD

**Issue by Prototypist1** [Colinwielga/Wanderer-Cordova#113]
aka a white shadow

**Comment by Prototypist1** [comment]
or maybe not a glow but it looks weird

**Comment by Prototypist1** [comment]
also this: 
![image](https://user-images.githubusercontent.com/41459272/106544727-0be0e880-64d6-11eb-95db-702685c049d5.png)

**Comment by toteos** [comment]
Linked pull request says it all. I didn't really follow the instructions from you, master, but I did make it look good. Bye!
