### ISSUE TITLE
Module's getId() value is used in two places

### ISSUE THREAD

**Issue by DeepwaterCreations** [Colinwielga/Wanderer-Cordova#2]
The div containing the whole module box, including the section header, uses this as its id.
The div nested immediately inside that div that isn't the section header div also uses it as its id.
Can only the inner one use it? That would make module-specific css easier. IDs are supposed to be unique, anyway.

**Comment by os-nicolas** [comment]
Good find. I agree that only the inner one should use it.

Do you want to make the change or should I?

**Comment by DeepwaterCreations** [comment]
You should go for it, since I'm working in a downstream repo.
