### ISSUE TITLE
Feature request: dark mode

### ISSUE THREAD

**Issue by toteos** [Colinwielga/Wanderer-Cordova#96]
Yo, came back from my sick-ass frappe-macha-ccino and thought, "whoa, my eyes are shot from this Japanese caffeine explosion! Gotta get me a dark mode on this product." So, I did just that! If we get 1 million likes, I'll make a mocha theme. Cheeers!

**Comment by Prototypist1** [comment]
🍵☕🍵☕

**Comment by Prototypist1** [comment]
ok but now do it better

**Comment by toteos** [comment]
Had a think in the nap pod, see the new refactor for dazzling beauty. Love to all. Cheeeeers with a hat on top. I'm off to the gym.
